apiVersion: v1
kind: PersistentVolume
metadata:
  name: auth-pv
spec:
  capacity:
    storage: 512Mi
  accessModes:
    - ReadWriteOnce         
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /data/shopflow/auth-db  
     
  nodeAffinity:
      required:
        nodeSelectorTerms:
          - matchExpressions:
              - key: shopflow/role
                operator: In
                values:
                  - storage 

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-pvc
  namespace: shopflow-dev 
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
  storageClassName: ""
  volumeName: auth-pv       # hint: this is how we manually bind to a specific PV