---
kubectl_version:   "v1.29.0"
minikube_version:  "v1.32.0"
minikube_driver:   "docker"
minikube_cpus:     2
minikube_memory:   "4096mb"

k8s_namespaces:
  - shopflow-dev
  - shopflow-prod

docker_hub_username: "salmahossam12"
shopflow_image_tag:  "latest"

# Path where repo will be cloned on the target machine
repo_url: "https://github.com/Salma-Hossam1/shopflow.git"
repo_dest: "/home/{{ ansible_user }}/shopflow"
k8s_manifests_dir: "{{ repo_dest }}/k8s"