apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-service-sa
  namespace: shopflow-dev

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: products-service-sa
  namespace: shopflow-dev

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: orders-service-sa
  namespace: shopflow-dev